name: Build ui
on:
  pull_request:
    branches: [main]
    paths:
    - apps/ui/**
  workflow_dispatch:
  
jobs:
    run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ui
    steps:

    - name: Checkout self
      uses: actions/checkout@v4
